### ISSUE TITLE
CRIAÇÃO DE PAGINAS E MELHORIAS NO LAYOUT

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#124]
- [x] CRIAR PAGINA FALE CONOSCO
- [x] CRIAR PAGINA DE RANKING ( INICIAR )
- [x] CORRIGIR AS DIVS NA PAGINA HOME
- [x] EXCLUIR IMAGEM DA ANTIGA PREFEITURA E INSERIR A NOVA
- [x] MAPA DO SITE
- [x] CORREÇÃO GRAMATICAL DOS NOMES NA PAGINA
- [x] PARCEIROS
- [x] QUEM SOMOS NÓS ?
- [x] DÚVIDAS ? IYODA

**Comment by juliotoscano** [comment]
Achei melhor o redimensionamento da imagem. Depois gostaria de um feedback para saber se permanece a alteração ou não.

**Comment by juliotoscano** [comment]
O que foi feito já pode dar o "merge" com a master pois não se encontra com erro.

**Comment by Micael0706** [comment]
@juliotoscano @jorgehclinhares @oseildo @Notrya  

Ok Julio, aceito, na próxima iteração faremos melhorias.
