### ISSUE TITLE
O levantamento de requisitos o contato com o cliente

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#13]
Requisitos são descrições do que o sistema irá realizar qual o desejo do cliente a sua necessidade, essa o qual o sistema venha a solucionar. Essa etapa define a finalidade do projeto e resumir a necessidade do cliente. A identificação consiste em entender em termos de requisitos e o que se espera obter como resultado, esse procedimento é geralmente realizado junto ao cliente.

É necessário realizar uma analise dos requisitos para tratar e avaliar inconsistências, ambigüidades, riscos e prioridades dos requisitos indicados na identificação.

**Comment by japm94** [comment]
Entendido.

**Comment by Micael0706** [comment]
Feito por Emmerson e Julio Toscano, ontem dia 08/10 com os clientes.
