### ISSUE TITLE
SCREENCAST DO PROJETO

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#139]
Ao final do projeto:
Um screencast curto (2-3 minutos) gravado pelo time mostrando um demo do projeto entregue após as 4 iterações. Aqui estão dois exemplos de projetos: Nurse Vacation Scheduler e o Pet Foster Home Finder. Recomendamos a postagem no YouTube ou em qualquer serviço similar.
Estamos estudando realizar ao final do semestre uma Sessão de Demos durante uma semana sem provas ou avaliações para que as equipes do semestre corrente possam exibir um poster e prover uma demonstração informal de seu projeto (vamos fornecer modelos / instruções) a uma sessão de pôsteres com a participação de seus clientes, amigos, professores e alunos, etc.
Uma breve "entrevista de saída" com o cliente, se pertinente, dando a sua impressão de como as coisas foram.

**Comment by Micael0706** [comment]
@japm94 @oseildo 

Segue para conhecimento a atividade.

**Comment by oseildo** [comment]
ok, ciente

Att,
Emmerson Santos

*Deus seja louvado!*


Em 8 de dezembro de 2015 11:06, Micael Souza <notifications@github.com>
escreveu:

**Comment by Micael0706** [comment]
@oseildo @japm94 

Emmerson e Julio, como estamos com relação a essa atividade ?

o que foi feito ? e o que está faltando ?

**Comment by Micael0706** [comment]
@jorgehclinhares 

LINK DO SCREEN CAST
https://www.youtube.com/watch?v=EQj7ixLzPhg
