### ISSUE TITLE
Realizar Plan in Poker e preencher Cronograma

### ISSUE THREAD

**Issue by juliotoscano** [Quality-Soft/qsproject#15]

**Comment by Micael0706** [comment]
Ok, ciente.

2015-10-08 14:32 GMT-03:00 juliotoscano <notifications@github.com>:

> Assigned #15 <https://github.com/Quality-Soft/qsproject/issues/15> to
> @Micael0706 <https://github.com/Micael0706>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/15#event-430587996>.
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by Micael0706** [comment]
Planning foi feito e definido as complexidades as tarefas de features, os valores usados foram de 1 a 3.

1 - simples
2 - dificil
3 - quarta guerra mundial

Links adicionados na pasta docs no arquivo planejamento.

Monitores favor revisar

**Comment by jorgehclinhares** [comment]
OK!
