### ISSUE TITLE
HU - PROCURAR MEI POR NOME OU DESCRIÇÃO DA ATIVIDADE

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#17]
Eu como uma organização,
para que possa encontrar um MEI, 
eu quero pesquisar por nome ou descrição da atividade

**Comment by Micael0706** [comment]
Ajustado nome Emmerson, conforme pedido.  @oseildo

**Comment by juliotoscano** [comment]
Como será uma única branch para os dois do grupo, por favor, antes da produção, verificar se há alguma criada. Se não houver, criar e notificar.

**Comment by Micael0706** [comment]
Exatamente Julio,

para conhecimento pessoal.

Em 4 de novembro de 2015 23:38, juliotoscano <notifications@github.com>
escreveu:

> Como será uma única branch para os dois do grupo, por favor, antes da
> produção, verificar se há alguma criada. Se não houver, criar e notificar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/17#issuecomment-153935640>
> .
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by juliotoscano** [comment]
Emmerson, branch criada. O nome é: issue_#17

**Comment by juliotoscano** [comment]
@oseildo , Consegui passar o parametro da pagina home para a pagina mei.

**Comment by juliotoscano** [comment]
@oseildo , resolvido o problema com a pesquisa realizada com o campo vazio.

**Comment by Micael0706** [comment]
.

**Comment by Micael0706** [comment]
Feature concluida e implementada.

@oseildo @juliotoscano @jorgehclinhares @Notrya @japm94 @pedroh100
