### ISSUE TITLE
Revisão do T.A - 24/09/2015

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#2]
Haverá uma reunião para alinharmos o TA no dia 23/09 e analisarmos o andamento das trilhas de cada um bem como ver novas atividades a serem feitas.

**Comment by Micael0706** [comment]
ok

**Comment by Micael0706** [comment]
Testando comentário para a equipe!!!


aguardo retorno.

**Comment by juliotoscano** [comment]
Ciente.

**Comment by Micael0706** [comment]
Atividade já realizada.

Att
Micael
