### ISSUE TITLE
CONSTRUIR PÁGINA PERFIL MEI

### ISSUE THREAD

**Issue by juliotoscano** [Quality-Soft/qsproject#29]
Fazer a estrutura e preencher com os componentes baseado no mockup. Não precisa estar conectado com outras páginas(ainda), basta fazer baseado na modelagem mas tentar manter o padrão parecido com a Home(O CSS e a estrutura).
P.S: A Home já está disponível para você reaproveitar alguns códigos.

**Comment by oseildo** [comment]
Já foi aceita?

**Comment by Micael0706** [comment]
Já ??? quando? quem? onde?

2015-10-12 21:55 GMT-03:00 oseildo <notifications@github.com>:

> Já foi aceita?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/29#issuecomment-147560978>
> .
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by jorgehclinhares** [comment]
É bom que apenas o gerente de projeto aceite atividades
