### ISSUE TITLE
Acesso ao drive

### ISSUE THREAD

**Issue by jorgehclinhares** [Quality-Soft/qsproject#32]
Estou sem permissão de visualização do drive de vocês, vocês poderiam liberar acesso para jhcl@cin.ufpe.br e para jorgehclinhares@gmail.com

**Comment by oseildo** [comment]
Permissão concedida.

Att,
Emmerson Santos

*Deus seja louvado!*


Em 14 de outubro de 2015 11:33, Jorge Linhares <notifications@github.com>
escreveu:

**Comment by jorgehclinhares** [comment]
ok!
