### ISSUE TITLE
FORMAS ESTIMULAR A PROSPECÇÃO DE MEI

### ISSUE THREAD

**Issue by oseildo** [Quality-Soft/qsproject#33]
A intenção eh criar uma pagina onde o empreendedor informal que tenha a pretensão de virar um MEI, insira seus dados para que o gestor da Sala do Empreendedor entre em contato com eles e guie o empreendedor a formalidade.

**Comment by Micael0706** [comment]
ciente.

Em 14 de outubro de 2015 17:36, oseildo <notifications@github.com> escreveu:

> A intenção eh criar uma pagina onde o empreendedor informal que tenha a
> pretensão de virar um MEI, insira seus dados para que o gestor da Sala do
> Empreendedor entre em contato com eles e guie o empreendedor a formalidade.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/33>.
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by juliotoscano** [comment]
Essa atividade está em aguardo esperando o documento da prefeitura com os passos de como se tornar um MEI.

**Comment by Micael0706** [comment]
@juliotoscano 

Julio, o documento já foi enviado, o que foi feito sobre esse assunto ?

**Comment by oseildo** [comment]
Ainda acho que isso não é tarefa nem pra gente, nem pra agora...

Att,
Emmerson Santos

*Deus seja louvado!*


2015-12-15 22:19 GMT-03:00 Micael Souza <notifications@github.com>:

**Comment by Micael0706** [comment]
Favor encerrar se for o caso, também acho que não, mas como está em aberto,
perguntei o andamento, só para conhecimento mesmo.

2015-12-16 8:30 GMT-03:00 oseildo <notifications@github.com>:

> Ainda acho que isso não é tarefa nem pra gente, nem pra agora...
>
> Att,
> Emmerson Santos
>
> *Deus seja louvado!*
>
>
> 2015-12-15 22:19 GMT-03:00 Micael Souza <notifications@github.com>:
>
> > @juliotoscano <https://github.com/juliotoscano>
> >
> > Julio, o documento já foi enviado, o que foi feito sobre esse assunto ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Quality-Soft/qsproject/issues/33#issuecomment-164953369
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/33#issuecomment-165074362>
> .
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by juliotoscano** [comment]
Sim sim. Ja foi entregue.

Em 16 de dezembro de 2015 12:06, Micael Souza <notifications@github.com>
escreveu:

> Favor encerrar se for o caso, também acho que não, mas como está em aberto,
> perguntei o andamento, só para conhecimento mesmo.
>
> 2015-12-16 8:30 GMT-03:00 oseildo <notifications@github.com>:
>
> > Ainda acho que isso não é tarefa nem pra gente, nem pra agora...
> >
> > Att,
> > Emmerson Santos
> >
> > *Deus seja louvado!*
> >
> >
> > 2015-12-15 22:19 GMT-03:00 Micael Souza <notifications@github.com>:
> >
> > > @juliotoscano <https://github.com/juliotoscano>
> > >
> > > Julio, o documento já foi enviado, o que foi feito sobre esse assunto ?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/Quality-Soft/qsproject/issues/33#issuecomment-164953369
> > >
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Quality-Soft/qsproject/issues/33#issuecomment-165074362
> >
> > .
> >
>
>
>
> --
>
> Atenciosamente,
>
> *Micael Santos*
> *Graduando em Sistemas de Informação*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/33#issuecomment-165135307>
> .
>



-- 
Att,
Júlio Toscano
