### ISSUE TITLE
Criação das Feature das histórias de Usuários

### ISSUE THREAD

**Issue by pedroh100** [Quality-Soft/qsproject#38]
Elaboração dos cenários das features.

**Comment by pedroh100** [comment]
Atividade concluída, mas com possíveis se necessárias atualizações

**Comment by pedroh100** [comment]
Link do documento > https://docs.google.com/document/d/194KKHGuz7Yx7B3SNJP4rziczgOC9z3irCQTNdFLu6gg/edit

**Comment by Micael0706** [comment]
Ok Pedro, eu vi o documento, melhorou! hehe



2015-10-26 23:42 GMT-03:00 pedroh100 <notifications@github.com>:

> Link do documento >
> https://docs.google.com/document/d/194KKHGuz7Yx7B3SNJP4rziczgOC9z3irCQTNdFLu6gg/edit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/38#issuecomment-151351954>
> .
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by jorgehclinhares** [comment]
@Micael0706 essas User Storys podem ser mapeadas em um único documento, versionado no github ?Assim facilita a correção pra gente.
