### ISSUE TITLE
Produzir a entrevista em vídeo de ~2 minutos onde o cliente (ou o P.O.) descreve o problema  que o aplicativo irá resolver;

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#4]
Produzir a entrevista em vídeo de ~2 minutos onde o cliente (ou o P.O.) descreve o problema  que o aplicativo irá resolver;

**Comment by Micael0706** [comment]
Nova atividade.

para conhecimento.

**Comment by jorgehclinhares** [comment]
Onde se encontra o vídeo?

**Comment by jorgehclinhares** [comment]
@Micael0706 eu não estou conseguindo localizar a entrevista que vocês realizaram com o cliente.

**Comment by jorgehclinhares** [comment]
Achei! OK!
