### ISSUE TITLE
 R8 - 21 OUT - REUNIÃO DE ALINHAMENTO

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#40]
Participantes:
Micael
Emmerson
Ayrton
Julio T.
Pedro

Pauta: 

- Mostrar o que foi feito e o que falta para finalizarmos a tarefa da Feature "Visualização das informações" 
- Mostrar as Sortyboards feitas 

Decisões: 

Link da foto: https://goo.gl/uZwDr6 

Layout - 
Modelos Feitos - 
Pesquisar - 
Listar- 
Show - 
Comentário -

**Comment by jorgehclinhares** [comment]
@Micael0706  lembrar de só add a tag docs mesmo, a review é quando nós monitores estamos corrigindo a atividade

**Comment by Micael0706** [comment]
@jorgehclinhares Ok Jorge esse tipo de atividade pode ser fechado por mim não é ?

**Comment by Micael0706** [comment]
@jorgehclinhares  Jorge, posso fechar ?

**Comment by Micael0706** [comment]
@jorgehclinhares  essa Issue, posso fechar ? está concluída .

**Comment by jorgehclinhares** [comment]
@Micael0706 sim Micael, desculpe a demora.

**Comment by jorgehclinhares** [comment]
Outra coisa, onde está o documento?

**Comment by jorgehclinhares** [comment]
@Micael0706 lembrar de dizer qual foi a opnião do cliente.
