### ISSUE TITLE
Correções Users Stories

### ISSUE THREAD

**Issue by jorgehclinhares** [Quality-Soft/qsproject#42]
Tem erro nessas histórias de usuário, precisa de algumas correções. A ideia é que elas sejam escritas em uma visão de desejo do cliente. A User story de número #23 está numa visão muito técnica, é bom lembrar que essas histórias são escritas para que qualquer leigo possa entender. 

Segue o link de ajuda: http://blog.myscrumhalf.com/2011/10/user-stories-o-que-sao-como-usar/

Qualquer coisa é só falar

**Comment by Micael0706** [comment]
@jorgehclinhares foi realizada a correção/ajuste de todas as histórias, favor validar.

**Comment by jorgehclinhares** [comment]
@Micael0706 ok!
