### ISSUE TITLE
Criar mockups e storyboards Lo-Fi das UI para essas histórias;

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#5]
Criar mockups e storyboards Lo-Fi das UI para essas histórias;

**Comment by Micael0706** [comment]
Nova atividade.

Para conhecimento.

**Comment by jorgehclinhares** [comment]
Uma atividade de documentação só poderá ser fechada pelos monitores, pois temos que analisar a documentação. Vocês podem usar a tag Review para indicar que a atividade necessita de avaliação dos monitores.

**Comment by Micael0706** [comment]
Jorge, favor validar o mockup.

https://gomockingbird.com/projects/ocwt8zc/4gXVnC

**Comment by jorgehclinhares** [comment]
OK!
