### ISSUE TITLE
HU - ADICIONAR COMENTÁRIOS

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#63]
Eu como cliente,
Para que eu possa saber sobre os serviços/produtos dos MEIS
Eu quero adicionar e visualizar os comentários dos usuários

- [x] Criação de Modelo, ,  
- [x] Associações com o MEI
- [x] Mostrar na view
- [x] teste de entrega ( não é bdd e tdd)

/play what

**Comment by juliotoscano** [comment]
Por favor, Julio e Ayrton, Lembrem-se que já existe o comentário criado e implementado. O que precisa ser feito nesse tópico é: fazer com que os comentários sejam apresentados de acordo com o mei específico.

**Comment by Micael0706** [comment]
@japm94 @Notrya 

Ayrton e Julio A, segue tarefa com as caixas para preenchimento de acordo com o que foi feito.

**Comment by Micael0706** [comment]
@jorgehclinhares @juliotoscano @japm94 @oseildo @pedroh100 @Notrya 

/play what
