### ISSUE TITLE
TESTE PARA HU #17 -

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#65]
Teste

Funcionalidade: Retornar resultado da pesquisa

Cenário: Deve retornar o resultado esperado pelo cliente e que estejam relacionados com os dados fornecidos.
Dado que eu estou na Home no campo de pesquisa
Quando eu preencher os dados de pesquisa no campo
E quando clicar no botão pesquisar
Então deve receber o resultado da pesquisa relacionados aos dados no campo.

**Comment by jorgehclinhares** [comment]
@Micael0706 podes disponibilzar o código do teste? grato.

**Comment by Micael0706** [comment]
@jorgehclinhares  Segue o link para acesso ao deretório nas pastas features e spec, são o BDD e TDD respectivamente, é isso que você precisa ? ou algo mais especifico ? print ?

https://github.com/Quality-Soft/qsproject/tree/master/projeto-01

**Comment by Micael0706** [comment]
@jorgehclinhares 

se for ajudar segue o que fizemos.

![testebdd2](https://cloud.githubusercontent.com/assets/11996796/11164785/e6f9c5d2-8ad8-11e5-87b9-752148119cec.png)


TDD

![testetdd3](https://cloud.githubusercontent.com/assets/11996796/11164796/b8974eca-8ad9-11e5-9ca5-1bef54577885.png)

![testetdd3-return](https://cloud.githubusercontent.com/assets/11996796/11164802/e736a7bc-8ad9-11e5-8dd9-13583f0ac8f7.png)

**Comment by jorgehclinhares** [comment]
@Micael0706  ok!
