### ISSUE TITLE
REUNIÃO DE DESENVOLVIMENTO COM O CLIENTE | ITERAÇÃO 1

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#77]
Link do documento desta reunião:

https://github.com/Quality-Soft/qsproject/blob/master/docs/reunioes/09.%20R9%20-%20Reuni%C3%A3o%20com%20o%20cliente%20-%2009Nov

**Comment by Micael0706** [comment]
@oseildo @juliotoscano @japm94 @pedroh100 @Notrya @jorgehclinhares

**Comment by Micael0706** [comment]
Documento da reunião atualizado com as informações da reunião e decisões tomadas.

@jorgehclinhares Jorge, favor revisar.

@oseildo @juliotoscano @japm94 @pedroh100 @Notrya @jorgehclinhares

**Comment by jorgehclinhares** [comment]
@Micael0706  ok!
