### ISSUE TITLE
CORREÇÃO DE BUGS

### ISSUE THREAD

**Issue by oseildo** [Quality-Soft/qsproject#81]
Os bugs são:

1. Redirecionamento para a página de comentários quando criamos um novo comentário
2. Botão voltar na página de show mei (exemplo redirect_to :back)
3. Impedir (remover) mensagem de sucesso quando o mei é editado
4. Imagem na home

**Comment by juliotoscano** [comment]
Os tópicos foram concluídos com excessão do segundo que se tornou inviável.

**Comment by Micael0706** [comment]
@juliotoscano verificado e validado Julio, estarei mesclando a branch com a master.

**Comment by Micael0706** [comment]
@juliotoscano @oseildo fiz correção do nome recife  para Recife na pagina home.

Issue sendo fechada.
