### ISSUE TITLE
POSTMORTEM - ITERAÇÃO 2

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#82]
Esta Issue referece ao documento de Postmortem da 2 iteração, segue abaixo o link do arquivo:

https://drive.google.com/open?id=1AsvWP8fHpj1I4f0nZLA04hQrhURLEoJ-NtRE0MsD83A

**Comment by jorgehclinhares** [comment]
@Micael0706 pode remover os comenta "<....>" em azul

**Comment by jorgehclinhares** [comment]
@Micael0706 está em desenvolvimento correto?

**Comment by Micael0706** [comment]
Corretissimo Jorge.

Em 16 de novembro de 2015 22:29, Jorge Linhares <notifications@github.com>
escreveu:

> @Micael0706 <https://github.com/Micael0706> está em desenvolvimento
> correto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quality-Soft/qsproject/issues/82#issuecomment-157231111>
> .
>



-- 

Atenciosamente,

*Micael Santos*
*Graduando em Sistemas de Informação*

**Comment by Micael0706** [comment]
@jorgehclinhares Jorge, boa tarde, tudo bem ?

documento concluido com sucesso.

favor revisar.

**Comment by Micael0706** [comment]
@Micael0706 teste.

**Comment by jorgehclinhares** [comment]
@Micael0706  ok!
