### ISSUE TITLE
POSTMORTEM - ITERACAO 1

### ISSUE THREAD

**Issue by Micael0706** [Quality-Soft/qsproject#83]

**Comment by Micael0706** [comment]
@jorgehclinhares  postmortem feito e entregue dia 04 de Novembro, em tempo hábil.

Link do documento ~> https://goo.gl/YfjXI4


![postmortem iteracao 1](https://cloud.githubusercontent.com/assets/11996796/11016877/9e5c4d0c-856c-11e5-9870-2cf722a35546.png)

**Comment by Micael0706** [comment]
foi entregue.

**Comment by jorgehclinhares** [comment]
@Micael0706 deixa que eu fecho esse tipo de atividade, pois o perigo é tu fechar e eu não ver o documento.

**Comment by Micael0706** [comment]
@jorgehclinhares Ok Jorge, obrigado.
