### ISSUE TITLE
HU - CATEGORIZAR E SELECIONAR MEI

### ISSUE THREAD

**Issue by oseildo** [Quality-Soft/qsproject#89]
Eu como uma organização,
Para que eu selecione os meis com atividades semelhantes
Eu quero selecioná-los por categoria.

- [x] Relacionar tabelas: MEI -act -occupation MEI-works-Jobs
- [x] Adaptar formulário de inserção
- [x] Adicionar select para capturar catogoria
- [x] Capturar valor da tabela
- [x] Conceder permissão de atributos para salvar
- [x] Conceder permissão de atributos para view

**Comment by juliotoscano** [comment]
1. Relacionar tabelas: MEI -act -occupation MEI-works-Jobs
2. Adaptar formulário de inserção
3. Adicionar select para capturar catogoria
4. Capturar valor da tabela
5. Conceder permissão de atributos para salvar
6. Conceder permissão de atributos para view

**Comment by Micael0706** [comment]
@juliotoscano @oseildo 

Emmerson e Julio, adicionei a caixa de checkbox direto na descrição inicial o que define e melhora a questão de não precisar colocar no checkbox pois será feito na mão por enquanto.

Obrigado!
