### ISSUE TITLE
MELHORIAS NO LAYOUT

### ISSUE THREAD

**Issue by juliotoscano** [Quality-Soft/qsproject#93]
1. Melhoria no layout da apresentação da mensagem "MEI não encontrado."(Aumentar também a fonte da letra.)
2. Padronizar sistema com as cores Azul e Amarelo.
3. Links na home com imagens para a sala do empreendedor e o site da prefeitura.
4. Soltar a imagem dos bonecos na home.
5. Deletar "Div" de cadastro.
6. Inserir "Div" Como fazer parte do mei a mei.

**Comment by Micael0706** [comment]
@juliotoscano 

Julio, ajustar a parte de querer ser divulgado como MEI para uma linha única e extendida com um passo a passo sobre como ser divulgado.

E outra abaixo, para aqueles que ainda não são MEIS apontando para informações.


É importante ter muitas informações para quem quer se tornar um MEI.

**Comment by juliotoscano** [comment]
Micael, pode fechar.
